name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
    - run: julia -e '
            using Pkg;
            Pkg.activate("."); Pkg.instantiate();
            Pkg.add(Pkg.PackageSpec(name="NodeJS")); using NodeJS;
            Pkg.add(Pkg.PackageSpec(name="Franklin", rev="master"));
            using Franklin;
            optimize(minify=false, prerender=false);'
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: __site # The folder the action should deploy.
